config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "recipes#index"
  # get "recipes", to: "recipes#index"
  resources :recipes
  get "recipes/busca", to: "recipes#busca"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def light?
    calories < 100
  end

  def self.created_at
    where('created_at <= ?', Time.now).order('created_at desc')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    if params[:query].present?
      @recipes = Recipe.where("name LIKE ?", "%#{params[:query]}%")
    else
      @recipes = Recipe.created_at
    end
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to @recipe
  end
  def new
    @recipe = Recipe.new
  end
  def create
    @recipe = Recipe.new(post_params)
    @recipe.save
    redirect_to @recipe
  end
  def post_params
    params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :kind, :portion, :duration, :poster)
  end
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url
  end
  def busca
    nome = params[:name]
    @recipes = Recipe.where "name like ?", "#{@nome}"
  end
  private

  def recipe_params
    params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :kind, :portion, :duration, :poster)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  # def formata_caloria(recipe)
  #   if recipe.light?
  #     content_tag(:strong, "Light - Menos de 100 calorias")
  #   else
  #     recipe.calories
  #   end
  # end
  def imagem(recipe)
    if recipe.poster.blank?
      image_tag('sem_imagem.png')
    else
      image_tag(recipe.poster)
    end
  end
end

app/views/layouts/_header.html.erb
    <%= nav_bar brand: "CookNow", brand_link: root_url do %>
    <% if user_signed_in? %>
      <%= menu_group do %>
        <%= menu_item "Nova Receita", new_recipe_path %>
        <%= menu_item "Sair", destroy_user_session_path, method: :delete, class:"nav-link" %>
      <% end %>
      
      <%= form_tag recipes_path, method: :get, class:"navbar-form navbar-right" do %>
        <%= text_field_tag :query, params[:query], class: "navbar-form", placeholder: "Encontre uma receita" %>
          <%= submit_tag "Buscar Receita", class: "btn btn-primary" %>
        <% end %>
    
      <% end %>
  
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CooknowReceitas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <p>
    <%= f.label :Nome %></br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Ingredientes %></br>
    <%= f.text_area :stuff, cols: 40, rows: 10 %>
  </p>
  <p>
    <%= f.label :Tipo %></br>
    <%= f.text_field :kind %>
  </p>
  <p>
    <%= f.label :Calorias %></br>
    <%= f.number_field :calories %>
  </p>
  <p>
    <%= f.label :Modo_de_Preparo %></br>
    <%= f.text_area :prepare_mode, cols: 40, rows: 10 %>
  </p>
  <p>
    <%= f.label :Tempo_de_Preparo %></br>
    <%= f.time_select :duration %>
  </p>
  <p>
    <%= f.label :Porções %></br>
    <%= f.text_field :portion %>
  </p>
  <p>
    <%= f.label :Poster %></br>
    <%= f.text_field :poster, placeholder: ".GIF, .JPEG ou .PNG" %>
  </p>
  <p>
    <%= f.submit %>
    <%= link_to "Cancel", root_path %>
  </p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editando Receitas</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>Cook Now - Receitas</h1>
<h3>Boas vindas ao sistema de gestão de refeições!<h3>
  
    <% if user_signed_in? %>

  <% @recipes.each do |recipe| %>

    <article>
      <header>
        <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
        <%# imagem(recipe) %>
      </header>
    </article>
  <% end %>
  <% else %>
  <h4>Entre com seu login e senha para ver as receitas!</h4>
       <%= button_to "Sign In", new_user_session_path, class:"btn btn-primary" %>

  <% end %>

app/views/recipes/new.html.erb
<h1>Criando Nova Receita</h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
 <article>
  <header>
    <h3><%= @recipe.name %></h3>
        <%= imagem(@recipe) %>
  </header>
 
  <p>
    <i><b>Tipo:</b></i> <%= @recipe.kind %>
  </p>
  <p>
    <i><b>Ingredientes:</b></i> <%= @recipe.stuff %>
  </p>
  <p>
    <i><b>Calorias:</b></i> <%= @recipe.calories %>
  </p>
  <p>
    <i><b>Modo de Preparo:</b></i> <%= @recipe.prepare_mode %>
  </p>
   <p>
    <i><b>Porções:</b></i> <%= @recipe.portion %>
  </p>
   <p>
    <i><b>Tempo de Preparo:</b></i> <%= @recipe.duration.strftime("%H:%M") %> min
  </p>
</article>

<div class="btn-group" role="group" aria-label="Exemplo básico">
  <button type="button" class="btn btn-secondary"><%= link_to "Editar Receita", edit_recipe_path(@recipe), class:"btn btn-warning" %></button>
  <button type="button" class="btn btn-secondary"><%= link_to "Deletar Receita", recipe_path(@recipe), method: :delete, class:"btn btn-danger", data: {confirm: "Remover receita?"}%></button>
</div>